import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css' 

const Contact = () => {
    return (
        <div className="contact">
          <Head>
            <title>Paz | Contact</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
            <div className="contact-title">
              Contacto
            </div>

            <div className="contact-socials">
              <ul className="contact-socials-list">

              <a href="https://api.whatsapp.com/send?phone=34677681241" >
                  <li className="contact-socials-list-item">
                    <img src="./icons/whatsapp.png" />
                  </li>
                </a>

                <a href="https://www.facebook.com/pazgutierrez.17" >
                  <li className="contact-socials-list-item">
                    <img src="./icons/facebook.png" />
                  </li>
                </a>

                <a href="https://instagram.com/paz_gutierrez_?igshid=YmMyMTA2M2Y=" >
                  <li className="contact-socials-list-item">
                    <img src="./icons/instagram.png" />
                  </li>
                </a>

                <a href="mailto:pazgutierrezespin@gmail.com" >
                  <li className="contact-socials-list-item">
                    <img src="./icons/gmail.png" />
                  </li>
                </a>
                


              </ul>


            </div>
            <div className="contact-image">
              <img src="./images/contact/mirrorPaz.JPG" className="contact-image-paz" />
            </div>
        </div>
        
      )
};

export default Contact;