import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css' ;
import { useState, useEffect } from 'react';
import axios from 'axios';

const Gallery = () => {

    return (
        <div className="gallery">
          <Head>
            <title>Paz | Gallery</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className="gallery-title">
            Gallery
          </div>  

          <div className="gallery-videos">
            <div className="gallery-subtitle">
              Videos
            </div>
          </div> 

          <div className="gallery-images">
            <div className="gallery-subtitle">
              Fotos
            </div>
            <div className="gallery-images-cards">

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image8.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image2.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image3.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image4.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image5.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image6.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image7.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image8.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image9.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image10.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image11.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image12.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image13.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image14.JPG' className="gallery-images-card-image"/>
              </div>

              <div className="gallery-images-card">
                <img src='/images/gallery/images/image15.JPG' className="gallery-images-card-image"/>
              </div>


            </div>

          </div>
        </div>
        
      )
};

export default Gallery;