import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css' 

const Gallery = () => {
    return (
        <div className={styles.container}>
          <Head>
            <title>Paz | Gallery</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main className={styles.main}>
            <div>
              Paz Gallery
            </div>
          </main>
    
        </div>
      )
};

export default Gallery;