import Head from 'next/head'
import Image from 'next/image'
import HomepageSwiper from '../components/swipers/homepageSwiper'


export default function Home() {
  return (
    <div className="homepage">
      <Head>
        <title>Paz Gutiérrez Espín</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="homepage-title">
        Paz Gutiérrez Espín
      </div>

      <div className="homepage-jobs">
        Actriz | Modela
      </div>

      <div className="homepage-swiper">
        <HomepageSwiper />
      </div>

    </div>
  )
}
